# Core
brew "git"
brew "zsh"
brew "vim"

# Ruby / Rails
brew "rbenv"
brew "ruby-build"
brew "postgresql@17"
brew "redis"
brew "node"
brew "yarn"

# Python
brew "pyenv"

# Languages
brew "ruby"

# Containers !
brew "colima"
brew "docker"
brew "docker-compose"

# Can i has some AI?
brew "llama.cpp"
brew "ollama"
brew "gemini-cli"

# Fonts
cask "font-source-code-pro-for-powerline"
