# Core
brew "git"
brew "zsh"
brew "vim"

# Ruby / Rails
brew "rbenv"
brew "ruby-build"
brew "postgresql"
brew "redis"
brew "node"
brew "yarn"

# Python
brew "pyenv"

# Languages
brew "ruby"

# Docker
brew colima
brew docker
brew docker-compose

tap "homebrew/cask-fonts"
cask "font-source-code-pro-for-powerline"
